import React, {useEffect, useRef, useState} from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';
import { NAVER_CLIENT_ID, JURISDICTION_BUFFER_METERS } from './config.js';
import { JURISDICTION_DATA } from './data/jurisdiction.js';

function loadNaverScript(){return new Promise((resolve,reject)=>{if(window.naver?.maps)return resolve();const s=document.createElement('script');s.src=`https://oapi.map.naver.com/openapi/v3/maps.js?ncpKeyId=${NAVER_CLIENT_ID}&submodules=geocoder`;s.onload=resolve;s.onerror=reject;document.head.appendChild(s);});}
const R=6371000,toRad=d=>d*Math.PI/180;
function toXY(p,o){return{x:R*(toRad(p[1])-toRad(o[1]))*Math.cos(toRad(o[0])),y:R*(toRad(p[0])-toRad(o[0]))};}
function pointToSeg(p,a,b){const P=toXY(p,p),A=toXY(a,p),B=toXY(b,p),vx=B.x-A.x,vy=B.y-A.y,wx=P.x-A.x,wy=P.y-A.y,c1=vx*wx+vy*wy,c2=vx*vx+vy*vy,t=c2===0?0:Math.max(0,Math.min(1,c1/c2)),proj={x:A.x+t*vx,y:A.y+t*vy};return Math.hypot(P.x-proj.x,P.y-proj.y);}
function lineDistance(p,line){let m=Infinity;for(let i=0;i<line.length-1;i++)m=Math.min(m,pointToSeg(p,line[i],line[i+1]));return m;}
function nearest(latlng){let best=null;for(const road of JURISDICTION_DATA.roads){for(const segment of road.segments){const distance=lineDistance(latlng,segment.centerline);if(!best||distance<best.distance)best={road,segment,distance};}}return best;}
function allPts(){return JURISDICTION_DATA.roads.flatMap(r=>r.segments.flatMap(s=>s.centerline));}
function makeBounds(n,pts){const b=new n.maps.LatLngBounds();pts.forEach(p=>b.extend(new n.maps.LatLng(p[0],p[1])));return b;}
function findBuiltIn(q){const t=q.replaceAll(' ','').toLowerCase();for(const [name,latlng] of Object.entries(JURISDICTION_DATA.places)){const k=name.replaceAll(' ','').toLowerCase();if(k.includes(t)||t.includes(k))return{name,latlng};}for(const road of JURISDICTION_DATA.roads){const rn=road.name.replaceAll(' ','').toLowerCase();if(rn.includes(t)||t.includes(rn)){const pts=road.segments.flatMap(s=>s.centerline);return{name:road.name,latlng:pts[Math.floor(pts.length/2)]};}for(const segment of road.segments){const sn=segment.name.replaceAll(' ','').toLowerCase();if(sn.includes(t)||t.includes(sn))return{name:`${road.name} / ${segment.name}`,latlng:segment.centerline[Math.floor(segment.centerline.length/2)]};}}return null;}
function App(){
const mapDiv=useRef(null),map=useRef(null),markers=useRef([]),lines=useRef([]);const[ready,setReady]=useState(false),[query,setQuery]=useState(''),[status,setStatus]=useState('검색어를 입력하세요. 예: 청담대교, 한남IC, 성산대교, 서울숲'),[result,setResult]=useState(null),[activeRoad,setActiveRoad]=useState('all');
useEffect(()=>{loadNaverScript().then(()=>{const n=window.naver;map.current=new n.maps.Map(mapDiv.current,{center:new n.maps.LatLng(37.545,127.02),zoom:11,mapTypeControl:true});setReady(true);drawRoads('all');map.current.fitBounds(makeBounds(n,allPts()));}).catch(()=>setStatus('네이버 지도 로딩 실패: Client ID / Web 서비스 URL을 확인하세요.'));},[]);
useEffect(()=>{if(ready)drawRoads(activeRoad);},[activeRoad,ready]);
function clear(){markers.current.forEach(m=>m.setMap(null));markers.current=[];lines.current.forEach(l=>l.setMap(null));lines.current=[];}
function drawRoads(filter='all'){if(!map.current)return;clear();const n=window.naver;JURISDICTION_DATA.roads.filter(r=>filter==='all'||r.id===filter).forEach((road,ri)=>{road.segments.forEach(seg=>{const line=new n.maps.Polyline({map:map.current,path:seg.centerline.map(p=>new n.maps.LatLng(p[0],p[1])),strokeWeight:filter==='all'?5:8,strokeOpacity:.75,strokeColor:filter==='all'?['#16a34a','#2563eb','#dc2626','#9333ea','#ea580c'][ri%5]:'#16a34a'});n.maps.Event.addListener(line,'click',()=>evaluate(seg.centerline[Math.floor(seg.centerline.length/2)],`${road.name} / ${seg.name}`));lines.current.push(line);});});}
function addMarker(latlng,title){const n=window.naver;const m=new n.maps.Marker({position:new n.maps.LatLng(latlng[0],latlng[1]),map:map.current,title});markers.current.push(m);}
function evaluate(latlng,title='검색 위치'){clear();drawRoads(activeRoad);addMarker(latlng,title);map.current.setCenter(new window.naver.maps.LatLng(latlng[0],latlng[1]));map.current.setZoom(15);const best=nearest(latlng),inside=best.distance<=JURISDICTION_BUFFER_METERS;setResult({latlng,title,best,inside});setStatus(`${title} 검색 완료. 가장 가까운 관할: ${best.road.name} / ${best.segment.name}, 거리 약 ${Math.round(best.distance)}m`);}
function search(){const q=query.trim();if(!q)return;const p=findBuiltIn(q);if(p)return evaluate(p.latlng,p.name);if(window.naver?.maps?.Service?.geocode){window.naver.maps.Service.geocode({query:q},(st,res)=>{if(st!==window.naver.maps.Service.Status.OK||!res?.v2?.addresses?.length){setStatus('검색 결과 없음. 주소는 네이버 Geocoding, 교량/IC/노선명은 내장 데이터로 검색합니다.');return;}const a=res.v2.addresses[0];evaluate([Number(a.y),Number(a.x)],a.roadAddress||a.jibunAddress||q);});}else setStatus('Geocoder 모듈 없음. 네이버 클라우드 Geocoding API 설정을 확인하세요.');}
function myLocation(){if(!navigator.geolocation){setStatus('현재 위치 기능을 사용할 수 없습니다.');return;}navigator.geolocation.getCurrentPosition(pos=>evaluate([pos.coords.latitude,pos.coords.longitude],'현재 위치'),()=>setStatus('현재 위치 권한이 거부되었거나 GPS를 찾지 못했습니다.'));}
function fitRoad(id){setActiveRoad(id);setTimeout(()=>{const n=window.naver;const road=JURISDICTION_DATA.roads.find(r=>r.id===id);const pts=id==='all'?allPts():road.segments.flatMap(s=>s.centerline);map.current.fitBounds(makeBounds(n,pts));},50);}
const badgeClass=!result?'maybe':result.inside?'ok':'no';const badgeText=!result?'검색 대기':result.inside?'✔ 관할구역입니다':'❌ 관할구역이 아닙니다';
return <div className="app"><div className="top"><div>🌳 GreenTBM 관할판별</div><div>네이버지도 검색 · PDF 관할 데이터</div></div><div className="main"><div style={{position:'relative',minHeight:0}}><div className="searchbox"><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')search()}} placeholder="장소/주소/교량/IC 검색"/><div className="btns"><button className="btn" onClick={search}>검색</button><button className="btn secondary" onClick={myLocation}>📍 현재 위치</button><button className="btn gray" onClick={()=>fitRoad('all')}>전체 보기</button></div><div className="btns">{['청담대교','한남IC','성산대교','가양대교','강일IC','서울숲'].map(x=><button key={x} className="btn gray" onClick={()=>{setQuery(x);const p=findBuiltIn(x);if(p)evaluate(p.latlng,p.name)}}>{x}</button>)}</div><div className="status">{status}</div></div><div ref={mapDiv} className="map"></div></div><div className="panel"><div className="card"><div className="title">관할 판별 결과</div><span className={`badge ${badgeClass}`}>{badgeText}</span>{result&&<><div className="row"><span>검색 위치</span><b>{result.title}</b></div><div className="row"><span>가장 가까운 노선</span><b>{result.best.road.name}</b></div><div className="row"><span>가장 가까운 구간</span><b>{result.best.segment.name}</b></div><div className="row"><span>노선까지 거리</span><b>{Math.round(result.best.distance)}m</b></div><div className="row"><span>판별 기준</span><b>{JURISDICTION_BUFFER_METERS}m 이내</b></div></>}{!result&&<div className="small">검색하면 이곳에 관할 여부가 표시됩니다.</div>}</div><div className="card"><div className="title">관할 노선 보기</div><div className="tabs"><button className={`tab ${activeRoad==='all'?'active':''}`} onClick={()=>fitRoad('all')}>전체</button>{JURISDICTION_DATA.roads.map(r=><button key={r.id} className={`tab ${activeRoad===r.id?'active':''}`} onClick={()=>fitRoad(r.id)}>{r.name}</button>)}</div></div><div className="card"><div className="title">가장 가까운 구간 상세</div>{result?<div className="seg"><div className="row"><span>노선</span><b>{result.best.road.name}</b></div><div className="row"><span>구간</span><b>{result.best.segment.name}</b></div><div className="row"><span>출처</span><b>{result.best.road.source}</b></div></div>:<div className="small">검색 후 표시됩니다.</div>}</div><div className="card list"><div className="title">등록된 관할 범위</div>{JURISDICTION_DATA.roads.map(r=><button key={r.id} onClick={()=>fitRoad(r.id)}>{r.name} · {r.segments.length}개 구간</button>)}</div><div className="card"><div className="title">CCTV · 날씨</div><a className="link" href="https://smartway.seoul.go.kr/web/main.view" target="_blank">SmartWay CCTV 열기</a><a className="link" href="https://www.weather.go.kr/w/index.do" target="_blank">기상청 날씨 열기</a><a className="link" href="https://www.weather.go.kr/w/weather/warning/status.do" target="_blank">기상특보 확인</a></div><div className="warn">현재 버전은 PDF 기반 노선 중심선 + 반경 판별 방식입니다. 실제 녹지 경계 GeoJSON을 만들면 더 정밀한 “구역 안/밖” 판별로 업그레이드할 수 있습니다.</div></div></div></div>;
}
createRoot(document.getElementById('root')).render(<App/>);
