
import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';
import {NAVER_CLIENT_ID, BUFFER_METERS} from './config.js';
import {DATA} from './data/jurisdiction.js';

const R=6371000, rad=d=>d*Math.PI/180;
function dist(a,b){const d1=rad(b[0]-a[0]),d2=rad(b[1]-a[1]);const x=Math.sin(d1/2)**2+Math.cos(rad(a[0]))*Math.cos(rad(b[0]))*Math.sin(d2/2)**2;return 2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function xy(p,o){return{x:R*(rad(p[1])-rad(o[1]))*Math.cos(rad(o[0])),y:R*(rad(p[0])-rad(o[0]))}}
function segDist(p,a,b){const P=xy(p,p),A=xy(a,p),B=xy(b,p),vx=B.x-A.x,vy=B.y-A.y,wx=P.x-A.x,wy=P.y-A.y,c2=vx*vx+vy*vy,t=c2?Math.max(0,Math.min(1,(vx*wx+vy*wy)/c2)):0;return Math.hypot(P.x-(A.x+t*vx),P.y-(A.y+t*vy))}
function lineDist(p,line){let m=1e9;for(let i=0;i<line.length-1;i++)m=Math.min(m,segDist(p,line[i],line[i+1]));return m}
function nearest(p){let best=null;for(const r of DATA.roads)for(const s of r.segments){const d=lineDist(p,s.centerline);if(!best||d<best.d)best={road:r,seg:s,d}}return best}
function loadScript(){return new Promise((ok,fail)=>{if(window.naver?.maps)return ok();const s=document.createElement('script');s.src=`https://oapi.map.naver.com/openapi/v3/maps.js?ncpKeyId=${NAVER_CLIENT_ID}&submodules=geocoder`;s.onload=ok;s.onerror=fail;document.head.appendChild(s)})}
function localPlace(q){const t=q.replaceAll(' ','').toLowerCase();for(const [n,p] of Object.entries(DATA.places)){const k=n.replaceAll(' ','').toLowerCase();if(k.includes(t)||t.includes(k))return{name:n,latlng:p,source:'내장 장소'}}for(const r of DATA.roads){const rk=r.name.replaceAll(' ','').toLowerCase();if(rk.includes(t)||t.includes(rk)){const pts=r.segments.flatMap(s=>s.centerline);return{name:r.name,latlng:pts[Math.floor(pts.length/2)],source:'내장 노선'}}for(const s of r.segments){const sk=s.name.replaceAll(' ','').toLowerCase();if(sk.includes(t)||t.includes(sk))return{name:`${r.name} / ${s.name}`,latlng:s.centerline[Math.floor(s.centerline.length/2)],source:'내장 구간'}}}return null}
function tm128ToLatLng(mapx,mapy){const n=window.naver;const p=new n.maps.Point(Number(mapx),Number(mapy));const ll=n.maps.TransCoord.fromTM128ToLatLng(p);return[ll.lat(),ll.lng()]}

function App(){
 const mapDiv=useRef(null),map=useRef(null),lines=useRef([]),markers=useRef([]);
 const [q,setQ]=useState(''),[status,setStatus]=useState('검색어 입력: 오목교역, 주소, 교량명, IC명'),[result,setResult]=useState(null),[cands,setCands]=useState([]);
 useEffect(()=>{loadScript().then(()=>{const n=window.naver;map.current=new n.maps.Map(mapDiv.current,{center:new n.maps.LatLng(37.54,126.98),zoom:11,mapTypeControl:true});drawLines()}).catch(()=>setStatus('네이버 지도 로딩 실패: Client ID와 Web 서비스 URL 확인'))},[]);
 function clearMarkers(){markers.current.forEach(m=>m.setMap(null));markers.current=[]}
 function drawLines(){if(!map.current)return;lines.current.forEach(l=>l.setMap(null));lines.current=[];const n=window.naver;DATA.roads.forEach((r,i)=>r.segments.forEach(s=>{const line=new n.maps.Polyline({map:map.current,path:s.centerline.map(p=>new n.maps.LatLng(p[0],p[1])),strokeColor:['#16a34a','#2563eb','#dc2626','#9333ea','#ea580c'][i%5],strokeWeight:5,strokeOpacity:.75});n.maps.Event.addListener(line,'click',()=>evalLoc(s.centerline[Math.floor(s.centerline.length/2)],`${r.name} / ${s.name}`));lines.current.push(line)}))}
 function evalLoc(p,name){clearMarkers();const n=window.naver;markers.current.push(new n.maps.Marker({map:map.current,position:new n.maps.LatLng(p[0],p[1]),title:name}));map.current.setCenter(new n.maps.LatLng(p[0],p[1]));map.current.setZoom(15);const b=nearest(p);setResult({p,name,b,inside:b.d<=BUFFER_METERS});setStatus(`${name} → 가장 가까운 관할: ${b.road.name} / ${b.seg.name}, 약 ${Math.round(b.d)}m`)}
 async function search(){const query=q.trim();if(!query)return;setCands([]);const local=localPlace(query);if(local){evalLoc(local.latlng,local.name);return}
   try{const r=await fetch(`/api/naver-place?query=${encodeURIComponent(query)}`);const data=await r.json();if(data.items?.length){const items=data.items.map(it=>({name:it.title.replace(/<[^>]+>/g,''),address:it.roadAddress||it.address,latlng:tm128ToLatLng(it.mapx,it.mapy),source:'네이버 지역검색'}));setCands(items);evalLoc(items[0].latlng,items[0].name);return}}catch(e){}
   if(window.naver?.maps?.Service?.geocode){window.naver.maps.Service.geocode({query},(st,res)=>{if(st!==window.naver.maps.Service.Status.OK||!res?.v2?.addresses?.length){setStatus('검색 결과 없음. 네이버 지역검색 API 환경변수 또는 주소 검색 설정을 확인하세요.');return}const a=res.v2.addresses[0];evalLoc([Number(a.y),Number(a.x)],a.roadAddress||a.jibunAddress||query)})}
 }
 function myLoc(){navigator.geolocation?.getCurrentPosition(p=>evalLoc([p.coords.latitude,p.coords.longitude],'현재 위치'),()=>setStatus('현재 위치 권한이 필요합니다.'))}
 const badge=!result?'검색 대기':result.inside?'✔ 관할구역입니다':'❌ 관할구역이 아닙니다';
 const cls=!result?'wait':result.inside?'ok':'no';
 return <div className="app"><div className="top"><div>🌳 GreenTBM 관할판별</div><div>네이버 지역검색 보완판</div></div><div className="main"><div style={{position:'relative',minHeight:0}}><div className="search"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')search()}} placeholder="예: 오목교역, 서울 영등포구..., 청담대교"/><div className="btns"><button className="btn" onClick={search}>검색</button><button className="btn light" onClick={myLoc}>📍 현재 위치</button><button className="btn gray" onClick={()=>window.open(`https://map.naver.com/p/search/${encodeURIComponent(q)}`)}>네이버지도에서 열기</button></div><div className="btns">{['오목교역','성산대교','한남IC','청담대교','서울숲'].map(x=><button className="btn gray" key={x} onClick={()=>{setQ(x);const p=localPlace(x);if(p)evalLoc(p.latlng,p.name)}}>{x}</button>)}</div><div className="status">{status}</div></div><div className="map" ref={mapDiv}></div></div><div className="panel"><div className="card"><div className="title">판별 결과</div><span className={`badge ${cls}`}>{badge}</span>{result&&<><div className="row"><span>검색 위치</span><b>{result.name}</b></div><div className="row"><span>노선</span><b>{result.b.road.name}</b></div><div className="row"><span>구간</span><b>{result.b.seg.name}</b></div><div className="row"><span>거리</span><b>{Math.round(result.b.d)}m</b></div><div className="row"><span>기준</span><b>{BUFFER_METERS}m 이내</b></div></>}</div>{cands.length>1&&<div className="card places"><div className="title">네이버 검색 후보</div>{cands.map((c,i)=><button key={i} onClick={()=>evalLoc(c.latlng,c.name)}>{c.name}<br/><span className="small">{c.address}</span></button>)}</div>}<div className="card"><div className="title">CCTV · 날씨</div><a className="link" target="_blank" href="https://smartway.seoul.go.kr/web/main.view">SmartWay CCTV</a><a className="link" target="_blank" href="https://www.weather.go.kr/w/index.do">기상청 날씨</a><a className="link" target="_blank" href="https://www.weather.go.kr/w/weather/warning/status.do">기상특보</a></div><div className="warn">오목교역 같은 장소명 검색은 네이버 Geocoding만으로는 안 됩니다. 이 버전은 Vercel 서버리스 지역검색 API를 추가했습니다. 환경변수 설정 전에는 내장 장소만 검색됩니다.</div></div></div></div>
}
createRoot(document.getElementById('root')).render(<App/>);
